CREATE TABLE tb_Utente (
	email VARCHAR(100) PRIMARY KEY,
	pwd VARCHAR(25) NOT NULL
)

ALTER TABLE tb_Utente ADD COLUMN preferiti VARCHAR(100)
ALTER TABLE tb_Utente ADD COLUMN ruolo VARCHAR(25)
ALTER TABLE tb_Utente ADD COLUMN punti INT(10)
